name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cache
        uses: actions/cache@v3.0.8
        with:
           path: /
           key: key
      - run: npm install -g bats
      - run: bats -v
